### PR TITLE
Data generation

### PR DESCRIPTION
**Pull request by ascherj**
The first part of my data generation. I have created a script, along with some helper functions, to generate 10M primary records—i.e., listings with just an 'id' field. The next step is to generate my image data.

### CODE REVIEW

**Comment by ascherj** [comment]
I started implementing my second script `generate_images.js`. Currently, I'm only able to generate one million records. I still need to work on scaling it to handle larger datasets and adding variance to randomize the amount of images generated per listing.

**Comment by rdkerr** [comment]
Go ahead and merge.

**Comment by ascherj** [comment]
Data generation is now finished. I updated `generate_images.js` to generate 5-10 image records per listing. I also created a shell script to automate the execution of each script and to generate 10M listing records and 50M-100M image records.

**Comment by rdkerr** [comment]
Everything looks good.  What kind of times are you getting for your seeds?

**Comment by ascherj** [comment]
image
Data generation takes a little over 7 minutes total.

**Comment by ascherj** [comment]
I fixed a bug where the id of the current image record being generated was not updating correctly. The fix involved reading from and saving to a file with the current id. Merging now.

**Pull request merged**
